version: '3.8'

services:
  app:
    image: mysql:latest
    container_name: mysql_todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1106
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - todolist_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_todolist
    environment:
      PMA_HOST: app
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - todolist_network

volumes:
  mysql_data: 
    driver: local 

networks:
  todolist_network:
    driver: bridge