version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_todolist
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      - todolist_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://app:3306/todolist_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1106
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  app:
    image: mysql:latest
    container_name: mysql_todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1106
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - todolist_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_todolist
    environment:
      PMA_HOST: app
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - todolist_network

volumes:
  mysql_data: 
    driver: local 

networks:
  todolist_network:
    driver: bridge