#Imagen base con Java 17
FROM eclipse-temurin:17-jdk

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Archivo JAR generado por Maven
COPY target/to-dolist-swagger-validation-0.0.1-SNAPSHOT.jar app.jar

# Expón el puerto que usa Spring Boot
EXPOSE 8080

# Comando para ejecutar la app
ENTRYPOINT ["java", "-jar", "app.jar"]
